[requirement]
# specify the minimal version of rapfi this config suits to
min_version = [0,31,1]

[general]
# Reload config file on each move
reload_config_each_move = false

# Clear TT after config is loaded
clear_hash_after_config_loaded = true

# Default thread number if not specified (0 means use all hardware concurrency)
default_thread_num = 1

# Output message mode (Options are [normal, brief, ucilike, none])
message_mode = "normal"

# Number of iterations after we found a mate
num_iteration_after_mate = 6

# Number of iterations after we found only one non-losing move at root
num_iteration_after_singular_root = 4

[model]
binary_file = "model210901-e05000.bin"
